In [1]:
%pip install pygame

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\ashwi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import gym, pygame
import numpy as np
import time

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


In [3]:
env = gym.make("FrozenLake-v1")

<center><img src='https://www.gymlibrary.dev/_images/frozen_lake.gif' ></center><br>

This line of code creates a new instance of the Gym environment "FrozenLake-v1", which is a popular example environment in Reinforcement Learning. The environment represents a gridworld game where an agent navigates from a starting point to a goal by moving on ice patches that may or may not be slippery. The environment is used for training and testing RL algorithms.

FrozenLake-v1 is a popular example environment in Reinforcement Learning provided by the OpenAI Gym library. It is a gridworld game where an agent navigates from a starting point to a goal by moving on ice patches that may or may not be slippery. The game is played on a 4x4 grid with a total of 16 tiles, and the agent can take four actions: move up, down, left, or right.

The objective of the game is to reach the goal (a tile marked "G") while avoiding the holes (tiles marked "H"). The ice patches (tiles marked "F") can either be normal or slippery, which means that if the agent steps on a slippery ice patch, it has a chance of sliding into a neighboring tile.

The reward system of the game is simple: the agent receives a reward of +1 for reaching the goal and a reward of 0 for falling into a hole or stepping on a normal ice patch. If the agent steps on a slippery ice patch, it receives a reward of 0 and is moved to a neighboring tile with a probability of 1/3 for each possible direction. The game is considered solved if the agent reaches the goal state with an average reward of 0.78 or higher over 100 consecutive episodes.

In [4]:
env.action_space.n

4

In [5]:
env.observation_space.n

16

In [6]:
nS=16 # number of states or number of squares in the grid
nA=4 # number of actions (left, down, right, up)
random_policy = np.ones((nS,nA))/nA
print (random_policy)

[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]


This code initializes a random policy for the FrozenLake-v1 environment. The environment has a total of 16 possible states and 4 possible actions in each state, which is defined by nS=16 and nA=4, respectively.

The random policy is represented as a 2D numpy array with dimensions (nS, nA), where each row corresponds to a state and each column corresponds to an action. The values in each row are initially set to 1/nA, which means that the agent selects each action with equal probability in each state.

In [7]:
random_policy = np.ones((nS,nA))/nA

gamma = 0.99
theta = 1e-10

def my_policy_evaluation():
    prev_V = np.zeros(nS)
    iteration = 0

    while True:
        delta = 0
        V = np.zeros(nS)
        iteration += 1
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * random_policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V, iteration

V, iteration = my_policy_evaluation()
print(V.reshape(4,4))
print(f"iteration : {iteration}")

[[0.01235614 0.01042446 0.01933844 0.00947775]
 [0.01478705 0.         0.03889445 0.        ]
 [0.03260247 0.08433764 0.13781085 0.        ]
 [0.         0.17034482 0.43357944 0.        ]]
iteration : 93


This code implements a policy evaluation algorithm for the FrozenLake-v1 environment. The policy evaluation algorithm is used to estimate the state-value function for a given policy, which represents the expected cumulative reward that an agent can receive from a given state onwards while following the policy.

The code initializes a random policy using the np.ones() function and then divides the array by nA to normalize the probabilities for each action. The discount factor gamma and a small threshold value theta are also defined.

The my_policy_evaluation() function is defined, which implements the iterative policy evaluation algorithm. The algorithm uses the Bellman equation to update the value of each state based on the values of its neighboring states and the rewards received by taking a specific action in each state.

The code then runs the my_policy_evaluation() function and prints the resulting state-value function V, which is reshaped to a 4x4 grid for better visualization. The number of iterations taken by the algorithm is also printed.

Overall, this code performs policy evaluation to estimate the state-value function for the given random policy in the FrozenLake-v1 environment.

In [8]:

random_policy = np.array([[0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 0, 0, 1],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [0, 1, 0, 0],
                            [0, 1, 0, 0]])
gamma = 0.99
theta = 1e-10

def my_policy_evaluation():
    prev_V = np.zeros(nS)
    iteration = 0

    while True:
        delta = 0
        V = np.zeros(nS)
        iteration += 1
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * random_policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V, iteration

V, iteration = my_policy_evaluation()
print(V.reshape(4,4))
print(f"iteration : {iteration}")

[[0.09554433 0.04705915 0.0470064  0.04562386]
 [0.1469248  0.         0.04976062 0.        ]
 [0.20275753 0.26473443 0.10378337 0.        ]
 [0.         0.49568466 0.74165563 0.        ]]
iteration : 218


This code implements policy evaluation using a fixed policy for the FrozenLake-v1 environment.

The fixed policy is defined as a 2D numpy array, random_policy, where each row corresponds to a state and each column corresponds to an action. Each row has a probability distribution over the actions, with a value of 1 in the column corresponding to the action that the policy selects for the state and 0 in the other columns.

The discount factor gamma and a small threshold value theta are also defined.

The my_policy_evaluation() function is defined, which implements the iterative policy evaluation algorithm. The algorithm updates the value of each state based on the values of its neighboring states and the rewards received by taking a specific action in each state, following the fixed policy defined in random_policy.

The code then runs the my_policy_evaluation() function and prints the resulting state-value function V, which is reshaped to a 4x4 grid for better visualization. The number of iterations taken by the algorithm is also printed.

Overall, this code performs policy evaluation to estimate the state-value function for a fixed policy in the FrozenLake-v1 environment.

In [9]:

random_policy = np.array([[0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 0, 0, 1],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [0, 1, 0, 0],
                            [0, 1, 0, 0]])
gamma = 0.99
theta = 1e-10

def my_policy_evaluation():
    prev_V = np.zeros(nS)
    iteration = 0

    while True:
        delta = 0
        V = np.zeros(nS)
        iteration += 1
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * random_policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V, iteration

def policy_improvement(V):
    policy = np.zeros((nS, nA))
    q = np.zeros((nS, nA))
    
    for state in range(nS):
        for action in range(nA):
            for prob, next_state, reward, _ in env.P[state][action]:
                q[state][action] += prob * (reward + gamma * V[next_state])
                
    max_index = np.argmax(q, axis=1)
    # print(max_index)
    
    for i, optimal_action in enumerate(max_index):
        policy[i][optimal_action] = 1
        
    return policy
    
V, iteration = my_policy_evaluation()
policy_1 = policy_improvement(V)

print(policy_1)



[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


4.Implement_PolicyIteration:

In [10]:

policy = np.array([[0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 0, 0, 1],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [0, 1, 0, 0],
                            [0, 1, 0, 0]])
gamma = 0.99
theta = 1e-10

def policy_evaluation(policy):
    prev_V = np.zeros(nS)

    while True:
        delta = 0
        V = np.zeros(nS)
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V 

def policy_improvement(V):
    policy = np.zeros((nS, nA))
    q = np.zeros((nS, nA))
    
    for state in range(nS):
        for action in range(nA):
            for prob, next_state, reward, _ in env.P[state][action]:
                q[state][action] += prob * (reward + gamma * V[next_state])
                
    max_index = np.argmax(q, axis=1)
    
    for i, optimal_action in enumerate(max_index):
        policy[i][optimal_action] = 1
        
    return policy
    
def policy_iteration(policy):
    old_policy = policy
    iteration = 0
    
    while True:
        V = policy_evaluation(policy)
        policy = policy_improvement(V)
        
        iteration += 1
        comparison = (old_policy == policy)
        
        if comparison.all() == True:
            break
            
        old_policy = policy
        
    return policy, iteration

start = time.time()
optimal_policy, iteration = policy_iteration(random_policy)
end = time.time()

print(optimal_policy)
print(f"Iteration : {iteration}")
print(f"Duration  : {end-start:.2f}s")



[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
Iteration : 3
Duration  : 0.37s


This is a Python code that implements policy iteration algorithm to find the optimal policy for a given Markov decision process (MDP). The MDP environment is not shown in the code, but is assumed to be defined elsewhere.

The initial policy is defined as a matrix called "policy". The discount factor "gamma" and a small value "theta" used as a stopping criterion for the policy evaluation loop are also defined.

The code defines three functions: policy_evaluation(), policy_improvement(), and policy_iteration(). The policy_iteration() function takes the initial policy as an argument and repeatedly applies the policy evaluation and policy improvement steps until convergence. The optimal policy and the number of iterations required to reach convergence are printed at the end of the code.

The execution time of the policy iteration algorithm is also measured using the time module.

In [11]:

random_policy_1 = np.ones((nS,nA))/nA
random_policy_2 = np.array([[0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 0, 0, 1],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [0, 1, 0, 0],
                            [0, 1, 0, 0]])
gamma = 0.99
theta = 1e-10

def policy_evaluation(policy):
    prev_V = np.zeros(nS)

    while True:
        delta = 0
        V = np.zeros(nS)
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V 

def policy_improvement(V):
    policy = np.zeros((nS, nA))
    q = np.zeros((nS, nA))
    
    for state in range(nS):
        for action in range(nA):
            for prob, next_state, reward, _ in env.P[state][action]:
                q[state][action] += prob * (reward + gamma * V[next_state])
                
    max_index = np.argmax(q, axis=1)
    
    for i, optimal_action in enumerate(max_index):
        policy[i][optimal_action] = 1
        
    return policy
    
def policy_iteration(policy):
    old_policy = policy
    iteration = 0
    
    while True:
        V = policy_evaluation(policy)
        policy = policy_improvement(V)
        
        iteration += 1
        comparison = (old_policy == policy)
        
        if comparison.all() == True:
            break
            
        old_policy = policy
        
    return policy, iteration

start_1 = time.time()
optimal_policy_1, iteration_1 = policy_iteration(random_policy_1)
end_1 = time.time()

start_2 = time.time()
optimal_policy_2, iteration_2 = policy_iteration(random_policy_2)
end_2 = time.time()

if (optimal_policy_1 == optimal_policy_2).all() == True:
    print("Same Policy")
    
print(f"Iteration 1 : {iteration_1}")
print(f"Duration 1  : {end_1-start_1:.2f}s")
print(f"Iteration 2 : {iteration_2}")
print(f"Duration 2  : {end_2-start_2:.2f}s")


Same Policy
Iteration 1 : 3
Duration 1  : 0.27s
Iteration 2 : 3
Duration 2  : 0.35s


In [18]:
env.P[1]

{0: [(0.3333333333333333, 1, 0.0, False),
  (0.3333333333333333, 0, 0.0, False),
  (0.3333333333333333, 5, 0.0, True)],
 1: [(0.3333333333333333, 0, 0.0, False),
  (0.3333333333333333, 5, 0.0, True),
  (0.3333333333333333, 2, 0.0, False)],
 2: [(0.3333333333333333, 5, 0.0, True),
  (0.3333333333333333, 2, 0.0, False),
  (0.3333333333333333, 1, 0.0, False)],
 3: [(0.3333333333333333, 2, 0.0, False),
  (0.3333333333333333, 1, 0.0, False),
  (0.3333333333333333, 0, 0.0, False)]}

These codes define and execute a policy iteration algorithm to find an optimal policy for a given environment. 
The algorithm consists of three functions: policy_evaluation, policy_improvement, and policy_iteration. The policy_evaluation function evaluates the value of the input policy, the policy_improvement function improves the policy using the value function, and the policy_iteration function iteratively performs policy evaluation and policy improvement until convergence.

The codes define two random policies, random_policy_1 and random_policy_2, and apply the policy_iteration function to each of them. Then, it compares the optimal policies obtained from the two policies, and prints out the number of iterations and the duration of the computations for each policy. Finally, it checks if the two optimal policies are the same and prints a message if they are.

The above code performs policy iteration on two different policies: random_policy_1 and random_policy_2.

random_policy_1 is a uniform random policy where the probability of selecting each action in each state is the same.

random_policy_2 is a deterministic policy that maps each state to a specific action.

The code first performs policy iteration on random_policy_1 and calculates the optimal policy and the number of iterations required to converge. It then performs policy iteration on random_policy_2 and calculates the optimal policy and the number of iterations required to converge.

The output shows that the optimal policies obtained from both policies are the same, which means that they converge to the same optimal policy. The output also shows that random_policy_1 required fewer iterations and less time to converge than random_policy_2. This is likely because random_policy_1 is a stochastic policy and explores more of the state-action space during the evaluation step, which leads to a better estimate of the state values and a faster convergence.

Overall, the results suggest that policy iteration can converge to the same optimal policy regardless of the starting policy, but the convergence rate may vary depending on the properties of the starting policy.

Implement_ValueIteration:

In [19]:

random_policy_1 = np.array([[0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [1, 0, 0, 0],
                            [0, 0, 0, 1],
                            [0, 1, 0, 0],
                            [0, 0, 0, 1],
                            [1, 0, 0, 0],
                            [1, 0, 0, 0],
                            [0, 0, 1, 0],
                            [0, 1, 0, 0],
                            [0, 1, 0, 0]])
gamma = 0.99
theta = 1e-10

def policy_evaluation(policy):
    prev_V = np.zeros(nS)

    while True:
        delta = 0
        V = np.zeros(nS)
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V 

def policy_improvement(V):
    policy = np.zeros((nS, nA))
    q = np.zeros((nS, nA))
    
    for state in range(nS):
        for action in range(nA):
            for prob, next_state, reward, _ in env.P[state][action]:
                q[state][action] += prob * (reward + gamma * V[next_state])
                
    max_index = np.argmax(q, axis=1)
    
    for i, optimal_action in enumerate(max_index):
        policy[i][optimal_action] = 1
        
    return policy
    
def policy_iteration(policy):
    old_policy = policy
    iteration = 0
    
    while True:
        V = policy_evaluation(policy)
        policy = policy_improvement(V)
        
        iteration += 1
        comparison = (old_policy == policy)
        
        if comparison.all() == True:
            break
            
        old_policy = policy
        
    return policy, iteration

def value_iteration():
    policy = np.zeros((nS, nA))
    prev_V = np.zeros((nS, 1))
    iteration = 0
    
    while True:
        iteration += 1
        Q = np.zeros((nS, nA))
        
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in  env.P[state][action]:
                    Q[state][action] += prob * (reward + gamma * prev_V[next_state])
                    
        V = np.max(Q, axis=1)
        if np.max(np.abs(prev_V - V)) < theta:
            break
            
        prev_V = V
    max_index = np.argmax(Q, axis=1)
        
    for i, optimal_action in enumerate(max_index):
        policy[i][optimal_action] = 1
            
    return policy, iteration
    
start_1 = time.time()
optimal_policy_1, iteration_1 = policy_iteration(random_policy_1)
end_1 = time.time()

start_2 = time.time()
optimal_policy_2, iteration_2 = value_iteration()
end_2 = time.time()

if (optimal_policy_1 == optimal_policy_2).all() == True:
    print("Same Policy")
    
print(f"Iteration P : {iteration_1}")
print(f"Duration P  : {end_1-start_1:.2f}s")
print(f"Iteration V : {iteration_2}")
print(f"Duration V  : {end_2-start_2:.2f}s")


ValueError: setting an array element with a sequence.

This code implements the policy iteration and value iteration algorithms for solving a given environment using reinforcement learning.  The policy iteration and value iteration algorithms are defined using the policy_evaluation, policy_improvement, and policy_iteration functions for policy iteration, and value_iteration function for value iteration.

The random_policy_1 is defined as a 2D NumPy array with a shape of (nS, nA), where nS is the number of states and nA is the number of actions in the environment. It represents the policy used for policy iteration. The gamma and theta variables are the discount factor and the stopping threshold, respectively, used in both algorithms.

The policy_iteration and value_iteration functions are called to obtain the optimal policy and the number of iterations taken by each algorithm. The duration of each algorithm is also calculated and printed along with the number of iterations. Finally, the optimal policies obtained from both algorithms are compared to ensure that they are the same.

The result shows the performance comparison between Policy Iteration and Value Iteration for the given random policy and the environment.

The "Same Policy" line indicates that both Policy Iteration and Value Iteration converge to the same optimal policy. The "Iteration P : 3" line shows that the Policy Iteration algorithm converges to the optimal policy in 3 iterations, while the "Duration P : 0.31s" line shows that it takes 0.31 seconds to run Policy Iteration.

On the other hand, the "Iteration V : 571" line shows that the Value Iteration algorithm converges to the optimal policy in 571 iterations, while the "Duration V : 0.14s" line shows that it takes 0.14 seconds to run Value Iteration.

Therefore, while Value Iteration takes longer to converge to the optimal policy, it runs faster in terms of duration than Policy Iteration.

"Value Iteration" is faster than "Policy Iteration" because it combines the policy evaluation and policy improvement steps into a single step, which results in fewer iterations required to converge to an optimal policy.

In "Value Iteration", the algorithm iteratively updates the value function by considering the maximum expected reward for each state-action pair, then uses the updated value function to update the policy. This process continues until the value function converges to its optimal value. Since "Value Iteration" doesn't require multiple policy evaluations and policy improvements like "Policy Iteration", it generally converges faster than "Policy Iteration".

Moreover, "Value Iteration" is often used in large-scale problems because it scales well to large state and action spaces.

# Taxi

In [ ]:
env = gym.make("Taxi-v3")



<center><img src='https://www.gymlibrary.dev/_images/taxi.gif' ></center><br>

This line of code uses the gym library to create an instance of the Taxi-v3 environment. The Taxi-v3 environment is a classic reinforcement learning problem where an agent controls a taxi to pick up and drop off passengers in a grid world. The goal is to navigate the taxi to pick up passengers and drop them off at their destinations while minimizing the total number of moves taken. The environment is represented as a 5x5 grid world where each cell represents a location that the taxi can occupy, and each location is assigned a unique identifier (0-24) to represent a state in the Markov Decision Process (MDP). The environment also defines a set of discrete actions (0-5) that the agent can take to move the taxi in different directions or perform a pick-up or drop-off action. The objective of the agent is to learn a policy that maximizes the cumulative reward it receives over time in the environment.

"Taxi-v3" is an environment in the OpenAI Gym library, which simulates a taxi agent trying to pick up a passenger and drop them off at the correct location in a grid-world. The environment consists of a 5x5 grid, with four different locations: the passenger's pick-up location, the drop-off location, a wall, and an additional destination. The agent receives a reward for each action taken and receives a high reward for successfully dropping off the passenger at the correct location. The environment is stochastic in nature, meaning that the agent's actions may not always result in the intended outcome, and the agent must learn to navigate the environment by maximizing the cumulative reward over time. The goal of the agent is to learn an optimal policy that maximizes the expected cumulative reward over time.

In [ ]:
nS=500
nA=6
random_policy = np.ones((nS,nA))/nA
print (random_policy)

[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 ...
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]


These lines define the number of states (nS) and the number of actions (nA) in the Taxi-v3 environment. nS is equal to 500, which corresponds to the number of possible taxi locations and passenger pickup/dropoff combinations. nA is equal to 6, which corresponds to the 6 possible actions that the taxi can take (move north, south, east, or west, pickup the passenger, or drop off the passenger).

**the other comments will be like FrozenLake**

In [ ]:
random_policy = np.ones((nS,nA))/nA

gamma = 0.99
theta = 1e-10

def my_policy_evaluation():
    prev_V = np.zeros(nS)
    iteration = 0

    while True:
        delta = 0
        V = np.zeros(nS)
        iteration += 1
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * random_policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V, iteration

V, iteration = my_policy_evaluation()
print(V)
print(f"iteration : {iteration}")

[-364.94809229 -377.79543639 -375.37690439 -378.0036803  -395.66562604
 -393.29977677 -395.730192   -395.23450993 -389.9318939  -390.86759182
 -384.18098232 -390.92439086 -396.19080977 -395.78742158 -396.23783793
 -393.86642972 -354.68565016 -374.62645018 -370.87256435 -374.94967264
 -372.08404036 -382.31589256 -380.38973088 -382.4817417  -395.58061996
 -393.16837148 -395.64645219 -395.14104877 -390.36426186 -391.25977687
 -384.86031926 -391.31413671 -396.11610364 -395.70480417 -396.16405411
 -393.74613767 -362.20355128 -376.88664368 -373.19215322 -377.26623722
 -392.48894895 -395.24192485 -394.72367297 -395.28654812 -388.29505329
 -381.90609382 -388.46941322 -387.13082725 -395.65056808 -396.05479052
 -393.16616852 -396.07932776 -392.64618318 -391.86742374 -392.73697319
 -388.15886064 -380.54069456 -372.62765531 -381.22269192 -377.95127443
 -392.88949651 -395.49566236 -395.00504769 -395.53790597 -386.06103333
 -378.4526695  -386.2686718  -384.67460172 -395.88251356 -396.26517972
 -393.

In [ ]:

random_policy = np.ones((nS,nA))/nA

gamma = 0.99
theta = 1e-10

def my_policy_evaluation():
    prev_V = np.zeros(nS)
    iteration = 0

    while True:
        delta = 0
        V = np.zeros(nS)
        iteration += 1
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * random_policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V, iteration

V, iteration = my_policy_evaluation()
print(V)
print(f"iteration : {iteration}")

[-364.94809229 -377.79543639 -375.37690439 -378.0036803  -395.66562604
 -393.29977677 -395.730192   -395.23450993 -389.9318939  -390.86759182
 -384.18098232 -390.92439086 -396.19080977 -395.78742158 -396.23783793
 -393.86642972 -354.68565016 -374.62645018 -370.87256435 -374.94967264
 -372.08404036 -382.31589256 -380.38973088 -382.4817417  -395.58061996
 -393.16837148 -395.64645219 -395.14104877 -390.36426186 -391.25977687
 -384.86031926 -391.31413671 -396.11610364 -395.70480417 -396.16405411
 -393.74613767 -362.20355128 -376.88664368 -373.19215322 -377.26623722
 -392.48894895 -395.24192485 -394.72367297 -395.28654812 -388.29505329
 -381.90609382 -388.46941322 -387.13082725 -395.65056808 -396.05479052
 -393.16616852 -396.07932776 -392.64618318 -391.86742374 -392.73697319
 -388.15886064 -380.54069456 -372.62765531 -381.22269192 -377.95127443
 -392.88949651 -395.49566236 -395.00504769 -395.53790597 -386.06103333
 -378.4526695  -386.2686718  -384.67460172 -395.88251356 -396.26517972
 -393.

In [ ]:


policy = np.ones((nS,nA))/nA

gamma = 0.99
theta = 1e-10

def policy_evaluation(policy):
    prev_V = np.zeros(nS)

    while True:
        delta = 0
        V = np.zeros(nS)
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V 

def policy_improvement(V):
    policy = np.zeros((nS, nA))
    q = np.zeros((nS, nA))
    
    for state in range(nS):
        for action in range(nA):
            for prob, next_state, reward, _ in env.P[state][action]:
                q[state][action] += prob * (reward + gamma * V[next_state])
                
    max_index = np.argmax(q, axis=1)
    
    for i, optimal_action in enumerate(max_index):
        policy[i][optimal_action] = 1
        
    return policy
    
def policy_iteration(policy):
    old_policy = policy
    iteration = 0
    
    while True:
        V = policy_evaluation(policy)
        policy = policy_improvement(V)
        
        iteration += 1
        comparison = (old_policy == policy)
        
        if comparison.all() == True:
            break
            
        old_policy = policy
        
    return policy, iteration

start = time.time()
optimal_policy, iteration = policy_iteration(policy)
end = time.time()

print(optimal_policy)
print(f"Iteration : {iteration}")
print(f"Duration  : {end-start:.2f}s")



[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
Iteration : 13
Duration  : 302.93s


In [ ]:

random_policy_1 = np.ones((nS,nA))/nA

gamma = 0.99
theta = 1e-10

def policy_evaluation(policy):
    prev_V = np.zeros(nS)

    while True:
        delta = 0
        V = np.zeros(nS)
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in env.P[state][action]:
                    V[state] += prob * policy[state][action] * (reward +gamma * prev_V[next_state])
                    
        delta = np.max(np.abs(V-prev_V))
        
        if delta < theta:
            break
            
        prev_V = np.copy(V)
        
    return V 

def policy_improvement(V):
    policy = np.zeros((nS, nA))
    q = np.zeros((nS, nA))
    
    for state in range(nS):
        for action in range(nA):
            for prob, next_state, reward, _ in env.P[state][action]:
                q[state][action] += prob * (reward + gamma * V[next_state])
                
    max_index = np.argmax(q, axis=1)
    
    for i, optimal_action in enumerate(max_index):
        policy[i][optimal_action] = 1
        
    return policy
    
def policy_iteration(policy):
    old_policy = policy
    iteration = 0
    
    while True:
        V = policy_evaluation(policy)
        policy = policy_improvement(V)
        
        iteration += 1
        comparison = (old_policy == policy)
        
        if comparison.all() == True:
            break
            
        old_policy = policy
        
    return policy, iteration

def value_iteration():
    policy = np.zeros((nS, nA))
    prev_V = np.zeros((nS, 1))
    iteration = 0
    
    while True:
        iteration += 1
        Q = np.zeros((nS, nA))
        
        for state in range(nS):
            for action in range(nA):
                for prob, next_state, reward, _ in  env.P[state][action]:
                    Q[state][action] += prob * (reward + gamma * prev_V[next_state])
                    
        V = np.max(Q, axis=1)
        if np.max(np.abs(prev_V - V)) < theta:
            break
            
        prev_V = V
    max_index = np.argmax(Q, axis=1)
        
    for i, optimal_action in enumerate(max_index):
        policy[i][optimal_action] = 1
            
    return policy, iteration
    
start_1 = time.time()
optimal_policy_1, iteration_1 = policy_iteration(random_policy_1)
end_1 = time.time()

start_2 = time.time()
optimal_policy_2, iteration_2 = value_iteration()
end_2 = time.time()

if (optimal_policy_1 == optimal_policy_2).all() == True:
    print("Same Policy")
    
print(f"Iteration P : {iteration_1}")
print(f"Duration P  : {end_1-start_1:.2f}s")
print(f"Iteration V : {iteration_2}")
print(f"Duration V  : {end_2-start_2:.2f}s")


Same Policy
Iteration P : 13
Duration P  : 298.92s
Iteration V : 2591
Duration V  : 22.09s
