# numpy
- 

In [4]:
import numpy as np
import pandas as pd
import seaborn as sls
import matplotlib as ptl

In [ ]:
# goal - create a 2x3 matrix
mylist23 = [
    [11,22.09,33],
    [44,55,66]
]

n23 = np.array(mylist23)
# n23 = np.array(mylist23, dtype=int)
print(n23)
print(n23.ndim) # number of dimention
print(n23.shape) # tuple indiacating access counts
print(n23.size) # total elements in array
print(n23.itemsize) # elemetn size - (int64 - dtype) 4 bytes in my case
print(n23.dtype)





[[11 22 33]
 [44 55 66]]
2
(2, 3)
6
4
int32


In [12]:
import sys
sys.version


'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [45]:
n1 = np.arange(10.2,20,2.5) # floating point numbers works with numpy arange but not with normal python range
n1 = np.arange(22.2,20,-0.5) # array([22.2, 21.7, 21.2, 20.7, 20.2])
n1 = np.arange(24).reshape(6,4) # reahape must be consistant -> 6*4 = 24
n1 = np.arange(24).reshape(6,-1) # reahape calculates when -1 is used
n1 = n1.flatten() # flatten it back to 1 dimention
n1

n64 = np.ones(shape=(6,4))
n64 = np.zeros(shape=(6,4))
n64 = np.identity(6)

np.random.seed(23)
n64 = np.random.randint(low=10, high=101,size=(6,4))
n64

n46 = n64.T
n46 = np.transpose(n64)
n46

array([[ 93,  41,  35,  22,  95,  31],
       [ 50,  86,  61,  59,  79,  58],
       [ 83,  49,  16,  76,  74,  51],
       [ 64, 100,  55,  85,  22,  89]])

In [55]:
np.random.seed(23)
n89 = np.random.randint(low=10, high=101, size=(8,9))
print(n89)
n89[0][0]
n89[0,0]
n89[2:5]

[[ 93  50  83  64  41  86  49 100  35]
 [ 61  16  55  22  59  76  85  95  79]
 [ 74  22  31  58  51  89 100  72  67]
 [ 29  43  69  49  25  46  75  11  53]
 [ 25  96  93  68  35  76  84  45  66]
 [ 23  70  32  48  41  88  10  31  16]
 [ 42  42  24  41  88  93  90  80  76]
 [ 92  95  65  37  72  53  84  81  52]]


array([[ 74,  22,  31,  58,  51,  89, 100,  72,  67],
       [ 29,  43,  69,  49,  25,  46,  75,  11,  53],
       [ 25,  96,  93,  68,  35,  76,  84,  45,  66]])

In [58]:
# row slicing, column slicing
n89[2:5, 2:8]

array([[ 31,  58,  51,  89, 100,  72],
       [ 69,  49,  25,  46,  75,  11],
       [ 93,  68,  35,  76,  84,  45]])

In [59]:
n89[1:6:2]

array([[61, 16, 55, 22, 59, 76, 85, 95, 79],
       [29, 43, 69, 49, 25, 46, 75, 11, 53],
       [23, 70, 32, 48, 41, 88, 10, 31, 16]])

In [63]:
# an list of indeces of required rows can be passed as a list
n89[[1,3,5,6]]

array([[61, 16, 55, 22, 59, 76, 85, 95, 79],
       [29, 43, 69, 49, 25, 46, 75, 11, 53],
       [23, 70, 32, 48, 41, 88, 10, 31, 16],
       [42, 42, 24, 41, 88, 93, 90, 80, 76]])

In [66]:
"""unintuitive and in pandas we will get 4 rows...
here the two lists are zipped together and their coordinates are considered
"""
n89[[1,3,5,6], [1,2,3,5]]



array([16, 69, 48, 93])

In [ ]:
# selictive choosing columnns and all rows

n89[:, 3:5] # cols 3, 4
n89[:, [3,4,-1]] # cols 3, 4 and last col

array([[64, 41, 35],
       [22, 59, 79],
       [58, 51, 67],
       [49, 25, 53],
       [68, 35, 66],
       [48, 41, 16],
       [41, 88, 76],
       [37, 72, 52]])

In [76]:
# all even nos greater than 50
mask1 = n89 %2 ==0
mask2 = n89 > 50
mask = mask1 & mask2
print(mask)
n89[mask]

[[False False False  True False  True False  True False]
 [False False False False False  True False False False]
 [ True False False  True False False  True  True False]
 [False False False False False False False False False]
 [False  True False  True False  True  True False  True]
 [False  True False False False  True False False False]
 [False False False False  True False  True  True  True]
 [ True False False False  True False  True False  True]]


array([ 64,  86, 100,  76,  74,  58, 100,  72,  96,  68,  76,  84,  66,
        70,  88,  88,  90,  80,  76,  92,  72,  84,  52])

In [ ]:
# values less that 25 or greater than 75
n89[ (n89<25) | (n89>75)  ] # for some reason the simple brackets are mandatory

array([ 93,  83,  86, 100,  16,  22,  76,  85,  95,  79,  22,  89, 100,
        11,  96,  93,  76,  84,  23,  88,  10,  16,  24,  88,  93,  90,
        80,  76,  92,  95,  84,  81])

In [84]:
# 
n89[0] = 0
n89[-3:] = 999

n89

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 61,  16,  55,  22,  59,  76,  85,  95,  79],
       [ 74,  22,  31,  58,  51,  89, 100,  72,  67],
       [ 29,  43,  69,  49,  25,  46,  75,  11,  53],
       [ 25,  96,  93,  68,  35,  76,  84,  45,  66],
       [999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999]])

In [88]:
n29 = np.arange(18).reshape(2,9)
n89[[1,2]] = n29 # rows 1 and 2 are replaced with a different matrix
n89[n89>50] = 789
n89

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 29,  43, 789,  49,  25,  46, 789,  11, 789],
       [ 25, 789, 789, 789,  35, 789, 789,  45, 789],
       [789, 789, 789, 789, 789, 789, 789, 789, 789],
       [789, 789, 789, 789, 789, 789, 789, 789, 789],
       [789, 789, 789, 789, 789, 789, 789, 789, 789]])

In [ ]:
np.random.seed(23)
n34 = np.random.randint(low=2, high=10, size=(3,4))

print(n34)

np.sum(n34) # 68
np.sum(n34, axis=0) # array([19, 15, 20, 14]) -> y axis
np.sum(n34, axis=1) # array([18, 26, 24]) -> x axis

# max, min, mean, median, var(variance), std(standard deviation = sqrt(variance)) follow the above pattern


[[5 8 2 3]
 [8 2 9 7]
 [6 5 9 4]]


array([18, 26, 24])